openapi: 3.1.0
info:
  title: Local Runner
  version: "1.0.0"
servers:
  - url: https://a2201802c2a1.ngrok-free.app
paths:
  /healthz:
    get:
      operationId: health
      summary: Health check
      responses:
        "200":
          description: Service is OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
  /run:
    post:
      operationId: runTask
      summary: Run an approved local task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task]
              properties:
                task:
                  type: string
                  description: Name of the whitelisted task to run (e.g., "hello")
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  task: { type: string }
                  returncode: { type: integer }
                  stdout: { type: string }
                  stderr: { type: string }
