openapi: 3.0.3
info:
  title: Local Runner
  version: "1.0.0"
servers:
  - url: https://REPLACE_ME.tld
paths:
  /run:
    post:
      operationId: runTask
      summary: Run an approved local task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task]
              properties:
                task:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  task: { type: string }
                  returncode: { type: integer }
                  stdout: { type: string }
                  stderr: { type: string }

